services:
  postgres:
    image: postgres:18-bookworm
    container_name: staging-postgres
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_USER: staging_user
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: househub_staging
    volumes:
        - postgres_data:/var/lib/postgresql
    networks:
      - staging_network

networks:
  staging_network:
    external: true
volumes:
  postgres_data:
